FROM golang:1.25-alpine

WORKDIR /app

# Установка необходимых пакетов
RUN apk add --no-cache git curl

# Установка Air для hot reload
RUN go install github.com/air-verse/air@latest

# Копируем go.mod и go.sum
COPY go.mod go.sum ./
RUN go mod download

# Копируем исходный код
COPY . .

# Команда запуска через Air
CMD ["air", "-c", ".air.toml"]
